version: 1

sources:
  - uri: "rtsp://192.168.9.146:18554/stream3"
    enabled: true

models:
  detector: "configs/config_infer_primary_peoplenet.txt"
  tracker:  "configs/config_tracker_NvDCF.yml"

output:
  mode: zmq
  endpoint: "tcp://*:5555"
  # mode: stdout               # uncomment for local debugging
  # mode: file                 # write JSONL to disk
  # file: /tmp/edge_retail_events.jsonl
